import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { cn } from "@/lib/utils";
import { MatchResultProvider } from "@/components/match-result-provider";
import { CriteriaSelector } from "@/components/criteria-selector";
import { TestList } from "@/components/test-list";
import Nav from "@/components/nav";

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        notoSans.variable,
      )}
    >
      <body className="h-full flex flex-col p-4">
        <Nav />
        <Suspense>
          <MatchResultProvider>
            <div className="flex grow gap-4 min-h-0">
              <CriteriaSelector />
              <TestList />
              <div className="flex-1 border-l border-muted ">{children}</div>
            </div>
          </MatchResultProvider>
        </Suspense>
      </body>
    </html>
  );
}
