import type {Metadata} from "next";
import {Geist, Geist_Mono, Google_Sans} from "next/font/google";
import "./globals.css";
import {Suspense} from "react";
import {cn} from "@/lib/utils";
import {MatchResultProvider} from "@/components/match-result-provider";
import {CriteriaSelector} from "@/components/criteria-selector";
import {TestList} from "@/components/test-list";
import Nav from "@/components/nav";
import CriteriaDrawer from "@/components/criteria-drawer";

const googleSans = Google_Sans({subsets: ['latin'], variable: '--font-sans'})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        googleSans.variable,
      )}
    >
      <body className="h-full flex flex-col px-2 md:px-4 relative">
        <Nav />
        <Suspense>
          <MatchResultProvider>
            <div className="flex grow flex-col md:flex-row md:gap-4 min-h-0">
              <div className="hidden md:block w-72 min-w-72 border-r border-muted">
                <CriteriaSelector />
              </div>
              <TestList />
              <div className="">{children}</div>
              <div className="md:hidden">
                <CriteriaDrawer/>
              </div>
            </div>
          </MatchResultProvider>
        </Suspense>
      </body>
    </html>
  );
}
