import type { Accepts } from "./dimensions";

interface Test {
  id: string;
  name: string;
  info: string;
  accepts: Accepts;
  minN?: number;
  maxN?: number;
  aka?: string;
}

export const tests: Test[] = [
  {
    id: "gauss-test",
    name: "Gauss-Test",
    info: "Das ist der Gauss Test, er Gausst sehr viel und ist auch sonst echt toll",
    accepts: {
      populationVariance: ["known", "unknown"],
      groupCount: ["one"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
    aka: "Z-Test",
  },
  {
    id: "one-sample-t-test",
    name: "1-Stichproben t-Test",
    info: "",
    accepts: {
      testFamily: ["parametric"],
      populationVariance: ["unknown"],
      groupCount: ["one"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
    maxN: 29,
  },
  {
    id: "two-sample-t-test",
    name: "2-Stichproben t-Test",
    info: "",
    accepts: {
      testFamily: ["parametric"],
      varianceHomogeneity: ["homogeneous"],
      sampleDependency: ["independent"],
      groupCount: ["two"],
      dataSeriesCount: ["two"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "welchs-t-test",
    name: "Welch-t-Test",
    info: "",
    accepts: {
      testFamily: ["parametric"],
      varianceHomogeneity: ["heterogeneous"],
      sampleDependency: ["independent"],
      groupCount: ["two"],
      dataSeriesCount: ["two"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
    aka: "Welchtest",
  },
  {
    id: "paired-t-test",
    name: "t-Test für abhängige Stichproben",
    info: "",
    accepts: {
      testFamily: ["parametric"],
      sampleDependency: ["dependent"],
      groupCount: ["two"],
      dataSeriesCount: ["two"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "one-way-anova",
    name: "ANOVA einfaktoriell",
    info: "",
    accepts: {
      factorCount: ["one"],
      groupCount: ["moreThanTwo"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "multi-factor-anova",
    name: "ANOVA mehrfaktoriell",
    info: "",
    accepts: {
      factorCount: ["two"],
      groupCount: ["moreThanTwo"],
      differenceRegarding: ["mean"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "chi-square-test-variance",
    name: "Chi^2 Test (X^2 Test)",
    info: "",
    accepts: {
      groupCount: ["one"],
      differenceRegarding: ["variance"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "f-test",
    name: "F-Test",
    info: "",
    accepts: {
      testFamily: ["parametric"],
      groupCount: ["two"],
      differenceRegarding: ["variance"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "chi-square-goodness-of-fit-normal-polytomous",
    name: "Chi^2 Anpassungstest (polytom) auf Normalverteilung",
    info: "",
    accepts: {
      differenceRegarding: ["distribution"],
      measurementScale: ["interval"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "wilcoxon-signed-rank-normal-approx",
    name: "Wilcoxon-Test (NV-Approximation)",
    info: "",
    accepts: {
      testFamily: ["nonparametric"],
      dataSeriesCount: ["two"],
      groupCount: ["one"],
      sampleDependency: ["dependent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    minN: 26,
  },
  {
    id: "wilcoxon-signed-rank-tied-rank-approx",
    name: "Wilcoxon-Test (Rangbindungs-Approximation)",
    info: "2 Datenreihen",
    accepts: {
      testFamily: ["nonparametric"],
      rankTies: ["present"],
      dataSeriesCount: ["two"],
      groupCount: ["one"],
      sampleDependency: ["dependent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    maxN: 25,
  },
  {
    id: "wilcoxon-signed-rank-exact",
    name: "Wilcoxon-Test",
    info: "2 Datenreihen",
    accepts: {
      rankTies: ["absent"],
      dataSeriesCount: ["two"],
      groupCount: ["one"],
      sampleDependency: ["dependent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    maxN: 25,
  },
  {
    id: "sign-test",
    name: "Vorzeichentest",
    info: "2 Datenreihen",
    accepts: {
      dataSeriesCount: ["two"],
      groupCount: ["one"],
      sampleDependency: ["dependent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "sign-test-normal-approx",
    name: "Vorzeichentest (NV-Approximation)",
    info: "2 Datenreihen",
    accepts: {
      dataSeriesCount: ["two"],
      groupCount: ["one"],
      sampleDependency: ["dependent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    minN: 36,
  },
  {
    id: "mann-whitney-u-normal-approx",
    name: "Mann-Whitney-U-Test (NV-Approximation)",
    info: "2 Datenreihen",
    accepts: {
      testFamily: ["nonparametric"],
      dataSeriesCount: ["two"],
      groupCount: ["two"],
      sampleDependency: ["independent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    minN: 21,
  },
  {
    id: "mann-whitney-u-tied-rank-approx",
    name: "Mann-Whitney-U-Test (Rangbindungs- Approximation)",
    info: "2 Datenreihen",
    accepts: {
      testFamily: ["nonparametric"],
      rankTies: ["present"],
      dataSeriesCount: ["two"],
      groupCount: ["two"],
      sampleDependency: ["independent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    maxN: 20,
  },
  {
    id: "mann-whitney-u-exact",
    name: "Mann-Whitney-U-Test",
    info: "2 Datenreihen",
    accepts: {
      testFamily: ["nonparametric"],
      rankTies: ["absent"],
      dataSeriesCount: ["two"],
      groupCount: ["two"],
      sampleDependency: ["independent"],
      measurementScale: ["ordinal"],
      researchQuestion: ["difference"],
    },
    maxN: 20,
  },
  {
    id: "binomial-test-normal-approx",
    name: "Binomialtest mit NV-Approximation",
    info: "",
    accepts: {
      normalApproximationValid: ["yes"],
      categoryCount: ["dichotomous"],
      groupCount: ["one"],
      sampleDependency: ["independent"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "binomial-test-exact",
    name: "Binomialtest exakt",
    info: "",
    accepts: {
      expectedCellFrequency: ["atMost10"],
      normalApproximationValid: ["no"],
      categoryCount: ["dichotomous"],
      groupCount: ["one"],
      sampleDependency: ["independent", "dependent"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
    maxN: 20,
  },
  {
    id: "chi-square-goodness-of-fit-dichotomous",
    name: "X²-Anpassungstest dichotom",
    info: "",
    accepts: {
      expectedCellFrequency: ["above10"],
      categoryCount: ["dichotomous"],
      sampleDependency: ["independent"],
      groupCount: ["one"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
    minN: 10,
  },
  {
    id: "chi-square-goodness-of-fit-polytomous",
    name: "Χ² -Anpassungstest (polytom)",
    info: "",
    accepts: {
      categoryCount: ["polytomous"],
      sampleDependency: ["independent"],
      groupCount: ["one"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "mcnemars-test",
    name: "Nc-Nemar-Test",
    info: "2 Datenreihen",
    accepts: {
      dataSeriesCount: ["two"],
      sampleDependency: ["dependent"],
      groupCount: ["one"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
    minN: 30,
  },
  {
    id: "mcnemars-test-continuity-correction",
    name: "Nc-Nemar-Test (Kontinuitätskorrektur)",
    info: "2 Datenreihen",
    accepts: {
      dataSeriesCount: ["two"],
      sampleDependency: ["dependent"],
      groupCount: ["one"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
    minN: 20,
    maxN: 30,
  },
  {
    id: "cochrans-q-test",
    name: "Cochran's Q Test",
    info: "2 Datenreihen",
    accepts: {
      dataSeriesCount: ["two"],
      sampleDependency: ["dependent"],
      groupCount: ["one"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "2x2-chi-square-goodness-of-fit",
    name: "4-Felder-X²-Anpassungstest",
    info: "",
    accepts: {
      dataSeriesCount: ["two"],
      marginalProbability: ["known"],
      groupCount: ["two"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "2x2-chi-square-independence",
    name: "4-Felder-X²-Unabhängigkeitstest",
    info: "",
    accepts: {
      dataSeriesCount: ["two"],
      marginalProbability: ["unknown"],
      groupCount: ["two"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "rxc-chi-square-test",
    name: "rxc-X²-Test",
    info: "",
    accepts: {
      groupCount: ["moreThanTwo"],
      measurementScale: ["nominal"],
      researchQuestion: ["difference"],
    },
  },
  {
    id: "correlation-test-deviation-from-zero",
    name: "Korrelations-Test Abweichung von 0",
    info: "",
    accepts: {
      correlationHypothesis: ["zero"],
      groupCount: ["one"],
      measurementScale: ["interval"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "correlation-test-deviation-from-nonzero-value",
    name: "Korrelations-Test Abweichung von Wert ≠ 0",
    info: "",
    accepts: {
      correlationHypothesis: ["nonzero"],
      groupCount: ["one"],
      measurementScale: ["interval"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "two-sample-correlation-test",
    name: "2-Stichproben-Korrelations-Test",
    info: "",
    accepts: {
      groupCount: ["two"],
      measurementScale: ["interval"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "spearman-correlation-test",
    name: "Spearman-Korrelations-Test",
    info: "",
    accepts: {
      measurementScale: ["ordinal"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "phi-coefficient",
    name: "Punkt-4-Felder-Korrelation (Phi-Koeffizient)",
    info: "",
    accepts: {
      categoryCount: ["dichotomous"],
      measurementScale: ["nominal"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "contingency-coefficient-c",
    name: "Kontingenz-Koeffizient C , über rxc-X²-Test",
    info: "",
    accepts: {
      categoryCount: ["polytomous"],
      measurementScale: ["nominal"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "cramers-v",
    name: "Cramer's Index CI, über rxc-X²-Test",
    info: "",
    accepts: {
      categoryCount: ["polytomous"],
      measurementScale: ["nominal"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "point-biserial-correlation",
    name: "Punkt-biserialer Korrelations-Test",
    info: "",
    accepts: {
      measurementScale: ["interval"],
      independentVariableScale: ["nominal"],
      researchQuestion: ["relationship"],
    },
  },
  {
    id: "equivalence-test-independent-samples",
    name: "Äquivalenztest für unabh. Stichproben",
    info: "",
    accepts: {
      sampleDependency: ["independent"],
      equivalenceEstablished: ["yes"],
      measurementScale: ["interval"],
      researchQuestion: ["equivalence"],
    },
  },
  {
    id: "equivalence-test-dependent-samples",
    name: "Äquivalenztest für abhängige Stichproben",
    info: "",
    accepts: {
      sampleDependency: ["dependent"],
      equivalenceEstablished: ["yes"],
      measurementScale: ["interval"],
      researchQuestion: ["equivalence"],
    },
  },
  {
    // No measurementScale entry: the source listed every scale, which is the
    // same as not caring.
    id: "crutch-test-alpha-02",
    name: "Krückentest mit α = 0,2",
    info: "",
    accepts: {
      equivalenceEstablished: ["no"],
      researchQuestion: ["equivalence"],
    },
  },
];
